### PR TITLE
Trying to fix a->b, b->a does not throw

### PR DESCRIPTION
**Pull request by jasir**

### CODE REVIEW

**Comment by digilist** [comment]
Thank you for your pull requests. That's indeed a case I haven't considered yet.

I just looked into it and the way I see it, the main problem here is that no root node is detected. That happens the graph is a circle. So imho, it would be a better solution to check if no root node was found. Would you like to change this? Otherwise I'll fix it the next days.

And please try to adapt the coding style of the project. I am following PSR-1 and 2.

**Comment by jasir** [comment]
Thank you!

ad PSR-1: hopefully fixed, sorry about that

ad root nodes:

I was not able to fix it that way, but I think it is correct solution. But please consider:

a -> b
b -> a
c -> d

... there will be one correct root, c

**Comment by jasir** [comment]
I have added one more test that should pass with 

a->b 
b->a 
c->d 

(possible) problem.

**Comment by digilist** [comment]
Okay, here you have multiple independent subgraphs and you are right, the library should support that.

You validate the result by sorting the nodes and comparing them with the available ones. Wouldn't it be easier to just count and look if both arrays have the same number of nodes? I don't see a case in which that does not work. Because if there are less nodes in the resolved array, there was a circle which was not considered. If there are more nodes, there was a circle and nodes were considered multiple times. Both should not happen, so I think we can change this.

**Comment by jasir** [comment]
Thank you for your answer. I think you are right. At least tests are passing... 👍 
I have force-pushed this change to fix

**Comment by digilist** [comment]
Perfect, thank you :smiley:

**Pull request merged**
